### ISSUE TITLE
挺好用的，没啥事，纯进来感谢一下

### ISSUE THREAD

**Issue by MIDE-589** [malaohu/MobaXterm-GenKey#4]
特别是Docker版，方便，一拉一跑一开网页就齐活了
正如核心内容的作者[flygon2018](https://github.com/flygon2018)所说，这货的激活算法没啥技术含量，我也想付费成为正版用户的，只是一看这价，就吓尿了……罪过……

**Comment by malaohu** [comment]
哈哈哈。如果公司用可以让公司掏钱
