### ISSUE TITLE
Flask版本要改下，不然运行会报错

### ISSUE THREAD

**Issue by 373137461** [malaohu/MobaXterm-GenKey#8]
Flask版本要改下，不然运行会报错cannot import name 'escape' from 'jinja2'
Jinja 是 Fl​​ask 的依赖项，Flask V1.XX 使用escapeJinja 的模块，但是最近[在新版本的 Jinja](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0)escape中删除了对该模块的支持。

要解决此问题，只需在您的requirements.txt中更新到更新版本的 Flask V2.XX，其中 Flask 不再使用escape来自 Jinja 的模块。
[原帖](https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2)

requirements.txt内容改为Flask==2.1.0
解决

**Comment by malaohu** [comment]
好的，已经修改 谢谢老哥~
