### ISSUE TITLE
下载Flask报错，ERROR: Could not find a version that satisfies the requirement Flask==1.1.2 (from versions: none)

### ISSUE THREAD

**Issue by xiaoshiguangl** [malaohu/MobaXterm-GenKey#9]
使用豆瓣的下载flask 就不会报错了
pip3 install --no-cache-dir -r requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

**Comment by malaohu** [comment]
已经修改flask版本，重新部署试一试
